// AUTO-GENERATED by `cortextos ecosystem` — safe to re-run (idempotent: it
// emits this same portable file; only the instance/org fallback values are
// baked from the generator's options).
// Portable: paths resolve at LOAD time relative to this file and the user's
// home. Override any value with environment variables before `pm2 start`.

const path = require('path');
const os = require('os');
const fs = require('fs');

const FRAMEWORK_ROOT = process.env.CTX_FRAMEWORK_ROOT || __dirname;
const PROJECT_ROOT = process.env.CTX_PROJECT_ROOT || FRAMEWORK_ROOT;
const INSTANCE_ID = process.env.CTX_INSTANCE_ID || "default";
const CTX_ROOT = process.env.CTX_ROOT || path.join(os.homedir(), '.cortextos', INSTANCE_ID);
const CTX_ORG = process.env.CTX_ORG || "";

// Instance-suffix the pm2 process name for non-default instances so multiple
// instances run side-by-side. Default stays 'cortextos-daemon' (unchanged) so a
// second instance start never renames/restarts the running default fleet.
const DAEMON_PM2_NAME =
  INSTANCE_ID === 'default' ? 'cortextos-daemon' : `cortextos-daemon-${INSTANCE_ID}`;

// Dashboard (BUG-019): supervised by PM2 when present — restart-on-crash,
// ~/.pm2 logs, reboot survival via pm2 startup/save. Presence, platform, and
// the Windows npm-shim bypass (PM2 can't exec npm.cmd; point it at the local
// next binary instead) are resolved at LOAD time so this file works on any
// machine and checkout. `next dev` for laptops, `next start` when
// NODE_ENV=production (assumes `next build` has run).
const dashboardDir = path.join(FRAMEWORK_ROOT, 'dashboard');
const hasDashboard = fs.existsSync(path.join(dashboardDir, 'package.json'));
const isWindows = process.platform === 'win32';
const dashMode = process.env.NODE_ENV === 'production' ? 'start' : 'dev';
const nextBin = path.join(dashboardDir, 'node_modules', 'next', 'dist', 'bin', 'next');
const useNextBin = isWindows && fs.existsSync(nextBin);

const apps = [
  {
    name: DAEMON_PM2_NAME,
    script: path.join(FRAMEWORK_ROOT, 'dist', 'daemon.js'),
    args: `--instance ${INSTANCE_ID}`,
    cwd: FRAMEWORK_ROOT,
    env: {
      CTX_INSTANCE_ID: INSTANCE_ID,
      CTX_ROOT: CTX_ROOT,
      CTX_FRAMEWORK_ROOT: FRAMEWORK_ROOT,
      CTX_PROJECT_ROOT: PROJECT_ROOT,
      CTX_ORG: CTX_ORG,
      // Debug-only: set to '1' to enable SIGUSR2 signal → controlled
      // uncaughtException for testing the crash-visibility path
      // (.daemon-crashed markers + crash-loop operator Telegram alert).
      // Leave '0' in production. `kill -SIGUSR2 $(pm2 pid cortextos-daemon)`
      // then watch the operator chat for the crash-loop alert after 3
      // crashes in 15 min.
      CTX_DEBUG_ALLOW_CRASH_TRIGGER: '0',
    },
    // max_restarts + restart_delay is the ultimate crash-storm circuit
    // breaker. If the daemon dies 10 times faster than 5s apart, PM2
    // gives up — the fleet goes fully dead, requiring a manual
    // `pm2 restart cortextos-daemon`. That is intentional: storm
    // protection > fleet uptime during a pathological crash loop.
    // The daemon's uncaughtException handler (src/daemon/index.ts)
    // fires a Telegram alert to the operator at 3+ crashes in 15 min —
    // well before this circuit trips. Do NOT raise these values without
    // also strengthening the upstream fix; the 2026-04-22 storm is a
    // reminder that unchecked auto-restart amplifies one bug into a
    // fleet-wide outage.
    max_restarts: 10,
    restart_delay: 5000,
    autorestart: true,
  },
];

if (hasDashboard) {
  apps.push({
    name: 'cortextos-dashboard',
    script: useNextBin ? nextBin : 'npm',
    args: useNextBin ? dashMode : `run ${dashMode}`,
    cwd: dashboardDir,
    env: {
      PORT: process.env.PORT || '3000',
    },
    // Dashboard reads its real config from dashboard/.env.local — populated
    // by /onboarding Phase 7. PM2 just supervises the dashboard process.
    windowsHide: true,
    max_restarts: 50,
    restart_delay: 5000,
    autorestart: true,
  });
}

module.exports = { apps };
