import { Command } from 'commander';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { homedir } from 'os';
import { fileURLToPath } from 'url';

/**
 * Build the PORTABLE ecosystem.config.js content (night-queue audit fix,
 * task_1783987166988). The generator used to bake machine-specific absolute
 * paths at generate time, clobbering the portable tracked template on every
 * `cortextos ecosystem` run (setup auto-runs it) and dirtying the checkout.
 * Now ALL machine-specific resolution — paths, platform, dashboard presence,
 * the Windows npm-shim bypass — happens at LOAD time inside the emitted JS.
 * Only the instance/org fallback VALUES are baked, so generation is pure and
 * idempotent, and the default-options output is byte-identical to the tracked
 * ecosystem.config.js (drift-guarded by tests/unit/cli/ecosystem-portable).
 */
export function buildEcosystemConfig(opts: { instance: string; org: string }): string {
  return `// AUTO-GENERATED by \`cortextos ecosystem\` — safe to re-run (idempotent: it
// emits this same portable file; only the instance/org fallback values are
// baked from the generator's options).
// Portable: paths resolve at LOAD time relative to this file and the user's
// home. Override any value with environment variables before \`pm2 start\`.

const path = require('path');
const os = require('os');
const fs = require('fs');

const FRAMEWORK_ROOT = process.env.CTX_FRAMEWORK_ROOT || __dirname;
const PROJECT_ROOT = process.env.CTX_PROJECT_ROOT || FRAMEWORK_ROOT;
const INSTANCE_ID = process.env.CTX_INSTANCE_ID || ${JSON.stringify(opts.instance)};
const CTX_ROOT = process.env.CTX_ROOT || path.join(os.homedir(), '.cortextos', INSTANCE_ID);
const CTX_ORG = process.env.CTX_ORG || ${JSON.stringify(opts.org)};
// Org-level Slack Socket Mode credentials (SP3b). Scoped narrowly on purpose — see
// the restart-invocation note on the daemon app's \`env\` block below.
const SLACK_APP_TOKEN = process.env.SLACK_APP_TOKEN || '';
const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN || '';

// Instance-suffix the pm2 process name for non-default instances so multiple
// instances run side-by-side. Default stays 'cortextos-daemon' (unchanged) so a
// second instance start never renames/restarts the running default fleet.
const DAEMON_PM2_NAME =
  INSTANCE_ID === 'default' ? 'cortextos-daemon' : \`cortextos-daemon-\${INSTANCE_ID}\`;

// Dashboard (BUG-019): supervised by PM2 when present — restart-on-crash,
// ~/.pm2 logs, reboot survival via pm2 startup/save. Presence, platform, and
// the Windows npm-shim bypass (PM2 can't exec npm.cmd; point it at the local
// next binary instead) are resolved at LOAD time so this file works on any
// machine and checkout. \`next dev\` for laptops, \`next start\` when
// NODE_ENV=production (assumes \`next build\` has run).
const dashboardDir = path.join(FRAMEWORK_ROOT, 'dashboard');
const hasDashboard = fs.existsSync(path.join(dashboardDir, 'package.json'));
const isWindows = process.platform === 'win32';
const dashMode = process.env.NODE_ENV === 'production' ? 'start' : 'dev';
const nextBin = path.join(dashboardDir, 'node_modules', 'next', 'dist', 'bin', 'next');
const useNextBin = isWindows && fs.existsSync(nextBin);

const apps = [
  {
    name: DAEMON_PM2_NAME,
    script: path.join(FRAMEWORK_ROOT, 'dist', 'daemon.js'),
    args: \`--instance \${INSTANCE_ID}\`,
    cwd: FRAMEWORK_ROOT,
    // Restart with:
    //   SLACK_APP_TOKEN=$(cortex-secret get SLACK_APP_TOKEN --context conduit) \\
    //   SLACK_BOT_TOKEN=$(cortex-secret get SLACK_BOT_TOKEN --context conduit) \\
    //   pm2 restart ecosystem.config.js --update-env
    // NEVER \`pm2 restart cortextos-daemon --update-env\` (bare app name) from an
    // agent's own shell — that snapshots the ENTIRE calling environment into pm2's
    // stored copy for this process, unscoped, and leaked a real BOT_TOKEN +
    // CTX_AGENT_NAME into the daemon's own env this way on 2026-08-25
    // (task_1787663199029_25580749), making every agent look Telegram-capable to
    // hasTelegram()'s daemon-side check. Restarting via the ecosystem FILE
    // re-evaluates only the \`process.env.X\` reads this file explicitly makes —
    // anything else set in the calling shell (an agent's BOT_TOKEN, ALLOWED_USER,
    // etc.) is irrelevant regardless of what that shell contains.
    env: {
      CTX_INSTANCE_ID: INSTANCE_ID,
      CTX_ROOT: CTX_ROOT,
      CTX_FRAMEWORK_ROOT: FRAMEWORK_ROOT,
      CTX_PROJECT_ROOT: PROJECT_ROOT,
      CTX_ORG: CTX_ORG,
      SLACK_APP_TOKEN: SLACK_APP_TOKEN,
      SLACK_BOT_TOKEN: SLACK_BOT_TOKEN,
      // Debug-only: set to '1' to enable SIGUSR2 signal → controlled
      // uncaughtException for testing the crash-visibility path
      // (.daemon-crashed markers + crash-loop operator Telegram alert).
      // Leave '0' in production; enable temporarily to reproduce crash
      // paths during development. \`kill -SIGUSR2 $(pm2 pid cortextos-daemon)\`
      // then watch the operator chat for "🚨 CRITICAL: daemon crash-looping"
      // after 3 crashes in 15 min.
      CTX_DEBUG_ALLOW_CRASH_TRIGGER: '0',
    },
    // max_restarts + restart_delay is the ultimate crash-storm circuit
    // breaker. If the daemon dies 10 times faster than 5s apart, PM2
    // gives up — the fleet goes fully dead, requiring a manual
    // \`pm2 restart cortextos-daemon\`. That is intentional: storm
    // protection > fleet uptime during a pathological crash loop.
    // The daemon's uncaughtException handler (src/daemon/index.ts)
    // fires a Telegram alert to the operator at 3+ crashes in 15 min —
    // well before this circuit trips. Do NOT raise these values without
    // also strengthening the upstream fix; the 2026-04-22 storm is a
    // reminder that unchecked auto-restart amplifies one bug into a
    // fleet-wide outage.
    max_restarts: 10,
    restart_delay: 5000,
    autorestart: true,
  },
];

if (hasDashboard) {
  apps.push({
    // The dashboard was previously started ad-hoc (\`pm2 start npm -- run start\`
    // from dashboard/) and was NOT in this file, so it only ever had CTX_ROOT if
    // the starting shell happened to export it. On 2026-08-14 a pm2 resurrect
    // brought it back from the saved dump — which carries no CTX vars — and it
    // ran for 37 hours online, serving, and ingesting nothing.
    //
    // CTX_ROOT IS LOAD-BEARING HERE, and the failure is silent because two
    // modules disagree about what "unset" means:
    //   dashboard/src/lib/config.ts  DEFAULTS  to ~/.cortextos/<instance>
    //   dashboard/src/lib/db.ts      FALLS BACK to <cwd>/.data/
    // With CTX_ROOT unset the dashboard therefore reads the RIGHT files and
    // writes them to the WRONG database — a fresh empty one under dashboard/.data/
    // — while the real DB sits orphaned and frozen. Nothing errors, pm2 stays
    // green, and the UI just shows nothing.
    name: 'cortextos-dashboard',
    script: useNextBin ? nextBin : 'npm',
    args: useNextBin ? dashMode : \`run \${dashMode}\`,
    cwd: dashboardDir,
    env: {
      CTX_INSTANCE_ID: INSTANCE_ID,
      CTX_ROOT: CTX_ROOT,
      CTX_FRAMEWORK_ROOT: FRAMEWORK_ROOT,
      CTX_PROJECT_ROOT: PROJECT_ROOT,
      CTX_ORG: CTX_ORG,
      PORT: process.env.PORT || '3000',
    },
    // Dashboard reads its real config from dashboard/.env.local — populated
    // by /onboarding Phase 7. PM2 just supervises the dashboard process.
    windowsHide: true,
    max_restarts: 50,
    restart_delay: 5000,
    autorestart: true,
  });
}

module.exports = { apps };
`;
}

export const ecosystemCommand = new Command('ecosystem')
  .option('--instance <id>', 'Instance ID', 'default')
  .option('--org <name>', 'Organization name (auto-detected if not specified)')
  .option('--output <path>', 'Output file', 'ecosystem.config.js')
  .description('Generate PM2 ecosystem.config.js from agent configs')
  .action(async (options: { instance: string; org?: string; output: string }) => {
    // BUG-035 (companion fix): same project-root discovery as enable-agent.ts
    // so `cortextos ecosystem` works from outside ~/cortextos.
    let projectRoot: string;
    if (process.env.CTX_FRAMEWORK_ROOT) {
      projectRoot = process.env.CTX_FRAMEWORK_ROOT;
    } else if (process.env.CTX_PROJECT_ROOT) {
      projectRoot = process.env.CTX_PROJECT_ROOT;
    } else {
      const canonical = join(homedir(), 'cortextos');
      projectRoot = existsSync(join(canonical, 'orgs')) ? canonical : process.cwd();
    }

    // Find all agents
    const agents: Array<{ name: string; dir: string; org?: string }> = [];

    // Scan orgs/*/agents/* (shared agents) AND orgs/*/engineers/*/agents/* (namespaced agents)
    const orgsDir = join(projectRoot, 'orgs');
    if (existsSync(orgsDir)) {
      for (const org of readdirSync(orgsDir, { withFileTypes: true })) {
        if (!org.isDirectory()) continue;

        // Shared agents: orgs/<org>/agents/<name>
        const agentsDir = join(orgsDir, org.name, 'agents');
        if (existsSync(agentsDir)) {
          for (const agent of readdirSync(agentsDir, { withFileTypes: true })) {
            if (!agent.isDirectory()) continue;
            agents.push({ name: agent.name, dir: join(agentsDir, agent.name), org: org.name });
          }
        }

        // Namespaced (per-engineer) agents: orgs/<org>/engineers/<eng>/agents/<name>
        const engineersDir = join(orgsDir, org.name, 'engineers');
        if (existsSync(engineersDir)) {
          for (const eng of readdirSync(engineersDir, { withFileTypes: true })) {
            if (!eng.isDirectory()) continue;
            const nsAgentsDir = join(engineersDir, eng.name, 'agents');
            if (!existsSync(nsAgentsDir)) continue;
            for (const agent of readdirSync(nsAgentsDir, { withFileTypes: true })) {
              if (!agent.isDirectory()) continue;
              agents.push({
                name: `${eng.name}/${agent.name}`,
                dir: join(nsAgentsDir, agent.name),
                org: org.name,
              });
            }
          }
        }
      }
    }

    if (agents.length === 0) {
      console.warn(
        'Warning: no agents found in any org. Generating ecosystem.config.js with only the daemon entry; the daemon will pick up agents added later via `cortextos add-agent`.',
      );
    }

    // Determine org: use --org flag, or auto-detect from first agent found
    const detectedOrg = options.org || agents.find(a => a.org)?.org || '';

    // All machine-specific resolution now lives INSIDE the emitted file (see
    // buildEcosystemConfig) — generation is pure; only instance/org values bake.
    const content = buildEcosystemConfig({ instance: options.instance, org: detectedOrg });
    const hasDashboard = existsSync(join(projectRoot, 'dashboard', 'package.json'));

    writeFileSync(options.output, content, 'utf-8');
    console.log(`Generated ${options.output} with daemon (manages ${agents.length} agents)${hasDashboard ? ' + dashboard' : ''}`);
    console.log('\nStart with:');
    console.log(`  pm2 start ${options.output}`);
    console.log('  pm2 save');
  });

/**
 * PM2 process name for an agent. Namespaced agents ("aaron/dev") have the "/"
 * replaced with "-" so the name is unique across engineers and shell-safe.
 * Currently exported for future per-agent PM2 entries; the current ecosystem
 * generator emits a single `cortextos-daemon` entry that manages all agents.
 */
export function pm2ProcessName(org: string, agentName: string): string {
  return `${org}-${agentName.replace('/', '-')}`;
}
