import { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { resolveAgentDir } from '../utils/agent-dir.js';

export const goalsCommand = new Command('goals')
  .description('Manage goals.json and auto-generate GOALS.md for agents');

// cortextos goals generate-md --agent <name> --org <org>
goalsCommand
  .command('generate-md')
  .description('Regenerate GOALS.md from goals.json for an agent')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .action((options: { agent: string; org: string }) => {
    const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();

    if (!/^[A-Za-z0-9_-]+$/.test(options.agent) || !/^[A-Za-z0-9_-]+$/.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }

    const agentDir = resolveAgentDir(frameworkRoot, options.org, options.agent);
    const goalsJsonPath = join(agentDir, 'goals.json');
    const goalsMdPath = join(agentDir, 'GOALS.md');

    if (!existsSync(goalsJsonPath)) {
      process.stderr.write(`goals.json not found at ${goalsJsonPath}\n`);
      process.exit(1);
    }

    let data: Record<string, unknown>;
    try {
      data = JSON.parse(readFileSync(goalsJsonPath, 'utf-8'));
    } catch {
      process.stderr.write(`Failed to parse goals.json for ${options.agent}\n`);
      process.exit(1);
    }

    const goals = Array.isArray(data.goals) ? (data.goals as Array<string | { title: string }>) : [];
    const focus = typeof data.focus === 'string' ? data.focus : '';
    const bottleneck = typeof data.bottleneck === 'string' ? data.bottleneck : '';
    const updatedAt = typeof data.updated_at === 'string' ? data.updated_at : new Date().toISOString();
    const updatedBy = typeof data.updated_by === 'string' ? data.updated_by : '';

    const lines: string[] = [
      '# Goals',
      '',
      '> Auto-generated from goals.json. Do not edit this file directly.',
      `> To regenerate: \`cortextos goals generate-md --agent ${options.agent} --org ${options.org}\``,
      '',
      '## Focus',
      focus || '(not set — check with your orchestrator)',
      '',
      '## Goals',
    ];

    if (goals.length === 0) {
      lines.push('(none set — message your orchestrator to request today\'s goals)');
    } else {
      goals.forEach((g, i) => {
        const title = typeof g === 'string' ? g : (g as { title: string }).title;
        lines.push(`${i + 1}. ${title}`);
      });
    }

    lines.push(
      '',
      '## Bottleneck',
      bottleneck || '(none)',
      '',
      '## Updated',
      updatedBy ? `${updatedAt} (by ${updatedBy})` : updatedAt,
      '',
    );

    writeFileSync(goalsMdPath, lines.join('\n'), 'utf-8');
    console.log(`Generated GOALS.md for ${options.agent}`);
  });
