#!/usr/bin/env npx tsx

/**
 * CLI codegen script — fetches schemas from the gateway for all vendors
 * and generates TypeScript command files for the mcpgw CLI.
 *
 * Usage:
 *   MCPGW_URL=http://localhost:8080 MCPGW_TOKEN=<jwt> npx tsx scripts/generate-cli.ts
 *
 * Output: packages/cli/src/vendors/<vendor>.ts per vendor
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const GATEWAY_URL = process.env.MCPGW_URL ?? 'http://localhost:8080';
const TOKEN = process.env.MCPGW_TOKEN;
const OUTPUT_DIR = join(import.meta.dirname ?? '.', '..', 'packages', 'cli', 'src', 'vendors');

interface CliFlag {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

interface CliCommand {
  command: string;
  description: string;
  flags: CliFlag[];
}

interface SchemaResponse {
  vendor: string;
  vendorName: string;
  commands: CliCommand[];
}

// Vendors to generate schemas for — configure per deployment
const VENDORS = (process.env.MCPGW_VENDORS ?? '').split(',').map(v => v.trim()).filter(Boolean);

async function fetchSchema(vendor: string): Promise<SchemaResponse | null> {
  if (!TOKEN) {
    console.error('MCPGW_TOKEN env var required');
    process.exit(1);
  }

  try {
    const res = await fetch(`${GATEWAY_URL}/v1/${vendor}/cli/schema`, {
      headers: { Authorization: `Bearer ${TOKEN}` },
      signal: AbortSignal.timeout(15_000),
    });

    if (!res.ok) {
      console.warn(`  Skipping ${vendor}: HTTP ${res.status}`);
      return null;
    }

    return (await res.json()) as SchemaResponse;
  } catch (err) {
    console.warn(`  Skipping ${vendor}: ${err instanceof Error ? err.message : err}`);
    return null;
  }
}

function generateVendorFile(schema: SchemaResponse): string {
  const lines: string[] = [
    `// Auto-generated by scripts/generate-cli.ts — do not edit`,
    `// Vendor: ${schema.vendorName} (${schema.vendor})`,
    ``,
    `export const vendor = '${schema.vendor}';`,
    `export const vendorName = '${schema.vendorName}';`,
    ``,
    `export const commands = ${JSON.stringify(schema.commands, null, 2)} as const;`,
    ``,
  ];
  return lines.join('\n');
}

async function main(): Promise<void> {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  console.log(`Fetching schemas from ${GATEWAY_URL}...\n`);

  const indexLines: string[] = [
    `// Auto-generated by scripts/generate-cli.ts — do not edit`,
    ``,
  ];

  for (const vendor of VENDORS) {
    console.log(`  ${vendor}...`);
    const schema = await fetchSchema(vendor);
    if (!schema) continue;

    const filename = `${vendor}.ts`;
    writeFileSync(join(OUTPUT_DIR, filename), generateVendorFile(schema));
    console.log(`    → ${schema.commands.length} commands`);

    indexLines.push(`export * as ${vendor.replace(/-/g, '_')} from './${vendor}.js';`);
  }

  indexLines.push('');
  writeFileSync(join(OUTPUT_DIR, 'index.ts'), indexLines.join('\n'));

  console.log(`\nDone. Generated files in ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
